# Jekyll settings to tell jeckyll how to build your site

# Site settings
title: WenXingming Blog
SEOTitle: WenXingming 的博客 | WenXingming Blog
header-img: img/home-bg.png
description: "这里是 @wxm 的个人博客，与你一起发现更大的世界 | 要做一个普通人, 先安顿自己, 再帮助别人"
keyword: "wxm, WenXingming, Blog, 博客, 个人网站, 互联网, Web"
url: "https://wenxingming.github.io" # your host, for absolute URL
baseurl: "/Blog/" # for example, '/blog' if your blog hosted on 'host/blog'
# 更改 \js\sw-registration.js 的第39行

# 个人介绍信息
name: Xingming Wen
school-major: School&Major @ Xidian University, Computer Science
hometown: 信阳, 河南
email: 2801650811@qq.com
blog: "https://wenxingming.github.io/Blog/"
github_url: "https://github.com/WenXingming"
google_scholar_url: "./img/404-bg.png" # 暂时没有Google

# Publish posts or collection documents with a future date.
future: true

# SNS-Links settings, 见 /_includes/sns-links.html
RSS: false
github_username: WenXingming
bilibili_username: 436373208 # bilibili ID
# weibo_username: huxpro

# Build settings
highlighter: rouge # from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty # URL style: :year/:month/:day/:title.html(md)
paginate: 8  # paginate to 5 posts per page
exclude: # files to exclude when building the site
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
timezone: Asia/Shanghai # If you have timezone issue (e.g. #68) in China. 
# 使用这个需要安装 gem 'tzinfo'、gem 'tzinfo-data'，可以通过修改 Gemfile，再执行bundle install, 但这种方式不知为何安装不上; 最后还是通过手动 gem install xxx

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown, although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown # a free pure-ruby Markdown superset converter, which can prase markdown files
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# # Disqus settings, Disqus 评论系统
disqus_username: wxm

# Netease settings. 网易云跟帖已倒闭...
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# # Google Analytics
# ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "做一个普通人，先安顿自己，再帮助别人"
sidebar-avatar: ./img/self.jpg # use absolute URL, seeing it's used in both `/` and `/about/`; 我没有使用绝对路径，更改了文件 short-about.html

# Featured Tags
featured-tags: true         # whether or not using Feature-Tags
featured-condition-size: 10  # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "表弟胡炎博", href: "https://space.bilibili.com/437239346" },
    { title: "我是Rapper", href: "https://aidn.jp/mikuwarp/" },
    { title: "童年小霸王", href: "https://www.yikm.net/" },
    { title: "Optical-Toys", href: "https://optical.toys/" },
  ]
