# 启用：创建 workflows 文件夹放进去

name: Build and Deploy

on:
  push:
    branches: [master]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库内容
      uses: actions/checkout@v4

    - name: 设置 Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: 安装 gem 依赖环境
      run: bundle install

    - name: 构建项目
      run: bundle exec jekyll build # 使用 bundler 安装所有依赖后，所有的命令应该通过 bundle exec 来运行，以确保它们从本地的 bundle 中执行，而不是全局环境

    - name: 将结果发布到 GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # 指定 GitHub Pages 分支
        folder: _site  # 指定生成静态文件的目录



# name: 定义Github Actions构建和发布的触发动作(push代码、master)
# on:
#   push:
#     branches: [master]
# permissions:
#   contents: write

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code（前置准备：签出、读取 Github 仓库内容）
#       uses: actions/checkout@v4

# # 安装环境：https://github.com/actions/runner-images/blob/ubuntu22/20240708.1/images/ubuntu/Ubuntu2204-Readme.md 可以看到已经有了 Ruby 和 RubyGems
#     - name: 安装 gem 依赖
#       run: |
#         gem install jekyll
#         gem install jekyll-paginate
#         gem install tzinfo
#         gem install tzinfo-data
#         gem install bundler
#         bundle install

#     - name: 构建项目
#       run: jekyll build
 
#     # https://docs.github.com/zh/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89-github-actions-%E5%B7%A5%E4%BD%9C%E6%B5%81%E8%BF%9B%E8%A1%8C%E5%8F%91%E5%B8%83

#     # # 上传静态文件，很多地方好像没有？
#     # - name: Upload static pages（上传静态文件）
#     #   uses: actions/upload-pages-artifact
#     #   with:
#     #     path: _site  # 指定生成静态文件的目录, 通常是Jekyll这类静态站点生成器的默认输出目录
#     # # 发布到 GitHub Pages
#     # - name: Deploy to GitHub Pages（发布到 GitHub Pages）
#     #   uses: peaceiris/actions-gh-pages@v3
#     #   with:
#     #     github_token: ${{ secrets.GITHUB_TOKEN }}
#     #     publish_dir: _site
      
#       - name: 将结果发布到 GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: gh-pages  # 指定 GitHub Pages 分支
#           folder: _site  # 指定生成静态文件的目录