# 定义触发工作流程的条件：当有推送（push）操作发生在 master 分支时，相应的GitHub Actions工作流程将被触发
name: Build and Deploy（定义Github Actions构建和发布的触发动作）
on:
  push:
    branches: [master]
permissions:
  contents: write
# 定义了一个名为build的作业，将在GitHub提供的最新Ubuntu虚拟环境中执行
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code（前置准备：签出、读取 Github 仓库内容）
      uses: actions/checkout@v4

# 安装环境：https://github.com/actions/runner-images/blob/ubuntu22/20240708.1/images/ubuntu/Ubuntu2204-Readme.md 可以看到已经有了 Ruby 和 RubyGems
    - name: 安装 gem 依赖
      run: gem install jekyll bundler 
      run: bundle install # 利用 bundler 安装 Gemfile 中的依赖

    - name: 构建项目
      run: jekyll build # 生成静态文件
 
    # https://docs.github.com/zh/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89-github-actions-%E5%B7%A5%E4%BD%9C%E6%B5%81%E8%BF%9B%E8%A1%8C%E5%8F%91%E5%B8%83

    # # 上传静态文件，很多地方好像没有？
    # - name: Upload static pages（上传静态文件）
    #   uses: actions/upload-pages-artifact
    #   with:
    #     path: _site  # 指定生成静态文件的目录, 通常是Jekyll这类静态站点生成器的默认输出目录
    # # 发布到 GitHub Pages
    # - name: Deploy to GitHub Pages（发布到 GitHub Pages）
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: _site
      
      
      - name: 将结果发布到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 指定 GitHub Pages 分支
          folder: _site  # 指定生成静态文件的目录